### ISSUE TITLE
The cudnn isn't available

### ISSUE THREAD

**Issue by gforge** [anibali/docker-torch#3]
There seems to be an issue with libcudnn:

Step 26 : COPY libcudnn.so.4 /lib/libcudnn.so.4
lstat libcudnn.so.4: no such file or directory

I can't find any reference to cuDNN being downloaded so I guess something must have gotten lost in somewhere or am I missing something? I noticed that Kaixhin uses a different setup for [his cuDNN containers](https://github.com/Kaixhin/dockerfiles/blob/master/cudnn/cudnn_v7.5/Dockerfile): 

``` Dockerfile
# Install CUDA repo (needed for cuDNN)
ENV CUDA_REPO_PKG=cuda-repo-ubuntu1404_7.5-18_amd64.deb
RUN wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/$CUDA_REPO_PKG && \
  dpkg -i $CUDA_REPO_PKG

# Install cuDNN v4
ENV ML_REPO_PKG=nvidia-machine-learning-repo_4.0-2_amd64.deb
RUN wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/$ML_REPO_PKG && \
  dpkg -i $ML_REPO_PKG && \
  apt-get update && apt-get install -y libcudnn4 libcudnn4-dev
```

Btw - thanks for this excellent Torch docker. I've had issues with the docker --device setup but with this it seems to work out of the box!

**Comment by gforge** [comment]
The Kaixhin solution didn't quite work so I tried Nvidia's own code and it seems to do the job. Perhaps an even direct path would be to work directly with their cuDNN release `export BASE=nvidia/cuda:cudnn`. I'm not sure I understand why you haven't chosen that approach, I was confused at first to why I kept getting `Specify CUDA_TOOLKIT_ROOT_DIR` when I used the `-runtime` but now I understand that it seems that only the development branch contains the necessary dependencies. 

Btw - could you specify the license for this repo?

**Comment by anibali** [comment]
@gforge Sorry for the late, late reply. This completely flew under my radar as I wasn't watching this repository for some reason.

The CUDNN situation is tricky because of licensing issues - NVIDIA seems to want developers to register and log in before downloading the library. However, I agree that the manual download is clunky and since NVIDIA now provide CUDNN as part of an official Docker image I think switching the base is the best approach here.

As for the license - would an MIT license suffice?

**Comment by gforge** [comment]
Thanks! No worries about the delay. I've been running the nvidia-dockers and they seem to do the job.

The MIT license is great - I love your solution and shamelessly stole it in my [own implementation](https://github.com/gforge/Gocker) ;-)
